// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD30GS3ucw26YkSJC-bLQlHdmbfSuC70oc',
    appId: '1:1074591300137:web:daf722204e88c0ad257a38',
    messagingSenderId: '1074591300137',
    projectId: 'flutterfirebaseauth-4d9d4',
    authDomain: 'flutterfirebaseauth-4d9d4.firebaseapp.com',
    storageBucket: 'flutterfirebaseauth-4d9d4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA81UUsvswwWCM09gBTpnNBZLvw4XyMr4',
    appId: '1:1074591300137:android:47ef01fe975abf70257a38',
    messagingSenderId: '1074591300137',
    projectId: 'flutterfirebaseauth-4d9d4',
    storageBucket: 'flutterfirebaseauth-4d9d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdOgsJ1j2N9kfyeb9nYod3BtXlO8HBERs',
    appId: '1:1074591300137:ios:2a10560c7683dd72257a38',
    messagingSenderId: '1074591300137',
    projectId: 'flutterfirebaseauth-4d9d4',
    storageBucket: 'flutterfirebaseauth-4d9d4.appspot.com',
    iosClientId: '1074591300137-kt4b5bnbu0nk9uu9qrvevm7ifa3bpsan.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFirebase',
  );
}
